### PR TITLE
[17.0] [MIG] mgmtsystem_hazard_risk

### PR DESCRIPTION
**Pull request by ThinkopenDev**
Migration to 17.0
- Using new XML syntax, in views/res_config_settings_views.xml

### CODE REVIEW

**Review by mymage — CHANGES_REQUESTED** [review]
The pandoc-3.1.9-1-amd64.deb is crafty than you ;-) an it is still there.
In the mean time, align PR title to the standard, thanks.

**Comment by mymage** [comment]
> The pandoc-3.1.9-1-amd64.deb is crafty than you ;-) an it is still there. In the mean time, align PR title to the standard, thanks.

Sorry, I saw that the file was already there on the repository: I create an issue #585 to have info

**Comment by mymage** [comment]
Hi @ThinkopenDev, the repo was fixed (see #585).
Then I think you have to re-push this after a rebase. Thanks!

**Review by max3903 — APPROVED** [review]

**Pull request merged**
