### PR TITLE
[SEC] mgmtsystem_kpi, mgmtsystem_hazard: fix unsafe eval

### PR DESCRIPTION
**Pull request by gurneyalex**

### CODE REVIEW

**Comment by antespi** [comment]
:+1:

**Comment by max3903** [comment]
:+1:

**Comment by dreispt** [comment]
:+1:

**Comment by dreispt** [comment]
Build is failing because of a missing Python dependency, `unicodecsv`, introduced by OCA/server-tools.
Should be fixed by adding a requirements.txt to the server tools repo.
I'm fast-tracking the merge despite of this issue.

**Pull request merged**
