### PR TITLE
[FIX] Fix automatic install of work instruction template

### PR DESCRIPTION
**Pull request by Rad0van**
This just adds document_page_work_instruction as dependency for document_page_procedure to get it automatically installed as in 10.0

### CODE REVIEW

**Review by flachica — APPROVED** [review]

**Comment by ivantodorovich** [comment]
If there isn't a real dependency, I'm not sure it makes sense to add it. The user can install both modules

**Comment by Rad0van** [comment]
> If there isn't a real dependency, I'm not sure it makes sense to add it. The user can install both modules

@ivantodorovich all the document templates are installed through settings of the main module. This one does not have an option there. I was checking in older version how this was handled. In 10.0 it was dependency for document_page_procedure then it disappeared. So for the sake of completeness I opted to restore the dependency as in 10.0 Otherwise user would have to install it through main Apps management...

**Comment by ivantodorovich** [comment]
Maybe we should add an option to the res.config page instead :thinking: , so that it's installed like the other modules

**Comment by Rad0van** [comment]
> Maybe we should add an option to the res.config page instead 🤔 , so that it's installed like the other modules

That is an option as well. Should I do that?

**Comment by ivantodorovich** [comment]
I think it does make more sense than adding the dependancy, and it's consistent to how the other modules are installed.
You can repurpose this PR for this matter

**Comment by Rad0van** [comment]
> I think it does make more sense than adding the dependancy, and it's consistent to how the other modules are installed.
> You can repurpose this PR for this matter

@ivantodorovich OK, done. Should I squash the commits together? Also, #341 should be merged first I guess?

**Comment by ivantodorovich** [comment]
Great! Thanks :)
Yes please squash them

**Comment by Rad0van** [comment]
> Great! Thanks :)
> Yes please squash them

Hope I got it right...

**Comment by ivantodorovich** [comment]
Not quite :sweat_smile: 
We need only 1 commit here

**Comment by Rad0van** [comment]
I see only one. Am I wrong? Edit: I see now. Will fix.

**Comment by Rad0van** [comment]
> Not quite 😅
> We need only 1 commit here

Done. I hope.

**Review by ivantodorovich — APPROVED** [review]

**Pull request merged**
