### PR TITLE
[MIG] mgmtsystem_hazard: Migration to 14.0

### PR DESCRIPTION
**Pull request by YvanDotet**

### CODE REVIEW

**Review by dreispt — CHANGES_REQUESTED** [review]
Missing commit history.
Please follow the instruction on #384

**Comment by YvanDotet** [comment]
Hello @dreispt 
I open https://github.com/OCA/management-system/issues/384 but I don't know what to do.

Here is a git log : 
`commit 82badbd30dab93b723ca957ceb3b56ef77840813 (HEAD -> 14.0-mig-mgmtsystem_hazard, origin/14.0-mig-mgmtsystem_hazard)
Author: Dotet <Yvandotet@yahoo.fr>
Date:   Thu May 27 16:27:07 2021 +0200

    [MIG] mgmtsystem_hazrd: Migration to 14.0
    
    Update version and change contributor
    
    modify group to groups
    
    modification
    
    modification
    
    add html
    
    add html section
`

Thank you.

**Comment by marcelsavegnago** [comment]
> #384

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0

**Comment by dreispt** [comment]
Superseded by #391

**Comment by YvanDotet** [comment]
ok I was lost with github command sorry :D

**Pull request closed without merging**
