### PR TITLE
[17.0][MIG] document_page_procedure: Migration to 17.0

### PR DESCRIPTION
**Pull request by m1k3lm**
/ocabot migration document_page_procedure

### CODE REVIEW

**Comment by mymage** [comment]
@m1k3lm please re-push to check test

**Comment by m1k3lm** [comment]
@mymage Done!

**Review by mymage — APPROVED** [review]
LGTM

**Comment by mymage** [comment]
@OCA/management-systems-maintainers please remove stale label, thanks.

**Pull request merged**
