### PR TITLE
[MIG][17.0] mgmtsystem_review

### PR DESCRIPTION
**Pull request by EdgarRetes**
@max3903 

Dependencies:

- [x] #596

### CODE REVIEW

**Comment by bosd** [comment]
Can you please squash translation commits?

**Comment by EdgarRetes** [comment]
> Can you please squash translation commits?

Do you mean all previuos commits of the migration or just the ones that are related to translation???

**Comment by max3903** [comment]
@EdgarRetes Can you rebase? Deps have been merged.

**Review by max3903 — APPROVED** [review]

**Pull request merged**
