### PR TITLE
[11.0] [ADD] new module mgmsystem_extended

### PR DESCRIPTION
**Pull request by mymage**
Ref. #263

### CODE REVIEW

**Comment by max3903** [comment]
@mymage Can you please make one pull request per module? It's easier to review and quicker to merge.

**Comment by ivantodorovich** [comment]
> @mymage Can you please make one pull request per module? It's easier to review and quicker to merge.

this please :sweat_smile:

**Comment by mymage** [comment]
> @mymage Can you please make one pull request per module? It's easier to review and quicker to merge.

Done in #265 #266 #267

**Comment by mymage** [comment]
Hi @max3903, I think the tag 'needs fixing' can be cleared.

**Comment by mymage** [comment]
WIP: Give a look at [this comment](https://github.com/OCA/management-system/issues/263#issuecomment-555378322), splitting these PR in other two more specific.

**Comment by mymage** [comment]
This PR has been divided in 6 new ones: #265 #266 #267 #282 #283 #284, so I close this.

**Pull request closed without merging**
