### PR TITLE
Fix line lengths

### PR DESCRIPTION
**Pull request by bwrsandman**

### CODE REVIEW

**Comment by rvalyi** [comment]
:+1:  LGTM

**Comment by pedrobaeza** [comment]
It seems to be still some PEP8 errors.

**Comment by rvalyi** [comment]
Hehe "work in progress"

**Comment by bwrsandman** [comment]
Done

**Comment by pedrobaeza** [comment]
:+1:

**Comment by rvalyi** [comment]
hello @bwrsandman,

you've fixed all PEP-8 errors indeed.
Now it seems your repo has a dependency upon the OCA/knowledge repo that is missing and making the build fail.
Fix that before merging?

**Comment by bwrsandman** [comment]
@rvalyi that is done in #6

**Comment by rvalyi** [comment]
ok, sorry, didn't connect the the 2 issues.

:+1:

**Comment by gurneyalex** [comment]
:+1:

**Pull request merged**
