### PR TITLE
[17.0] [MIG] document_page_environment_manual

### PR DESCRIPTION
**Pull request by David-Luis-Mora**
This module depends on #569

### CODE REVIEW

**Comment by mymage** [comment]
Hi @David-Luis-Mora, the repo was fixed (see #585).
Then I think you have to re-push this after a rebase. Thanks!

**Comment by bosd** [comment]
@OCA-git-bot Seems to be taking a break.

**Comment by max3903** [comment]
> @OCA-git-bot Seems to be taking a break.

Must be summer vacation still...

**Pull request merged**
