### PR TITLE
[IMP] mgmtsystem_quality: Update CONTRIBUTORS.rst

### PR DESCRIPTION
**Pull request by max3903**

### CODE REVIEW

**Review by dreispt — APPROVED** [review]

**Comment by yassine-rhimi** [comment]
Dear OCA Community Members,

I trust this message finds you well. I am writing to bring your attention to a matter that requires immediate intervention. Currently, there are two pending commits awaiting merger and has not been deployed on [pypi.org](http://pypi.org/) since October .

Your swift cooperation in merging these commits and updating the module is crucial to ensuring that the latest changes are reflected. This will allow the community to benefit from the improvements that have been made.

Below are the details of the pending commits:

Management System Module:

Translation Commit Date: November 20, 2023
Last Version Update: October 11, 2023
Pypi Link: https://pypi.org/project/odoo-addon-mgmtsystem/16.0.1.0.0.8/
Translation Fr Link: https://github.com/OCA/management-system/tree/16.0/mgmtsystem/i18n


Product Pricelist Revision Module:

Translation Commit Date: November 15, 2023
Last Update: October 30, 2023
Pypi Link:  https://pypi.org/project/odoo-addon-product-pricelist-revision/    
Translation Fr Link: https://github.com/OCA/product-attribute/tree/16.0/product_pricelist_revision/i18n)
I kindly request your prompt attention to these matters and appreciate your cooperation in ensuring the timely deployment of the latest updates for the benefit of the entire community.

Thank you in advance for your support.

Best regards,

[Rhimi Yassine]

**Comment by dreispt** [comment]
@sbidoul Hi, there is a concern here that commits with translations coming from Weblate don't trigger PyPi releases.
Indeed, waiting for the next fix to be pushed to have the translations released is not a reliable process.
Any idea on how to handle this?

**Comment by sbidoul** [comment]
> Hi, there is a concern here that commits with translations coming from Weblate don't trigger PyPi releases. Indeed, waiting for the next fix to be pushed to have the translations released is not a reliable process. Any idea on how to handle this?

@dreispt the bot is doing a nightly release with all the main branches. So this is new and I'm noting to investigate this as soon as I can.

**Comment by sbidoul** [comment]
Also, I don't immediately see why your merge command failed. That is weird.

**Comment by dreispt** [comment]
Thank you @sbidoul .
Indeed, the bot's build is green. Trying again just in case.

/ocabot merge patch

**Comment by sbidoul** [comment]
This may explain things 
image

**Review by flotho — APPROVED** [review]
Hi, 
I sadly approve this PR 
@max3903 is leaving us ;-)

**Pull request merged**
