### PR TITLE
[13.0][IMP] mgmtsystem_nonconformity: enabling to create non-conformities from different models

### PR DESCRIPTION
**Pull request by albariera**
This PR adds the option to relate non_conformities with any other module. For example, if we want to relate a maintenance request with a non_conformity.

### CODE REVIEW

**Review by FernandoRomera — APPROVED** [review]

**Review by MRomeera — APPROVED** [review]

**Review by AntoniRomera — APPROVED** [review]

**Review by marcelsavegnago — APPROVED** [review]
@albariera Just as a suggestion, it would be interesting to increase test coverage.

**Review by etobella — APPROVED** [review]

**Comment by etobella** [comment]
@OCA/management-systems-maintainers

**Comment by etobella** [comment]
@OCA/management-systems-maintainers Can this be merged?

**Pull request merged**
