### PR TITLE
[13.0][MIG] mgmtsystem_action_claim

### PR DESCRIPTION
**Pull request by ludolelarge**
Link between Action and Claim

### CODE REVIEW

**Comment by max3903** [comment]
@ludolelarge If you follow the documentation on #262, you will get the history of commits from the previous branch, and not just one commit.

**Comment by ludolelarge** [comment]
Is there a member that could help me to create right pull request.
I upload mgmtsystem_claim necessary to work with mgmtsystem_action_claim. But all file related to mgmtsystem_claim where uploaded in my pull request (mgmtsystem_action_claim).
I don't understand how it work to create pull request by module ???

Sorry i m newer

**Comment by ludolelarge** [comment]
i can't remove the *.pyc file adding by error
i can't remove  mgmtsystem_claim/static/description/icon.png adding by error
Help please

**Comment by ludolelarge** [comment]
Is someone could help me ... Sorry for the question but im noob
Finaly i use command line to migrate but i  have this error

ludovic@Odoo:~/Github$ git checkout -b 13.0-mig-mgmtsystem_action_claim origin/13.0
fatal: Not a git repository (or any of the parent directories): .git

**Comment by dreispt** [comment]
@ludolelarge That command needs to run inside a local Git repo. You may need to first clone the repo, if you haven't done so.
My advice is to follow a tutorial on Git and get familiarized with it, and then come back this task.

**Pull request closed without merging**
