### PR TITLE
8.0 mgmtsystem environment

### PR DESCRIPTION
**Pull request by max3903**
Depends on 
- [x]  #27 
- [x] #17  
- [x] #52  
- [x]  #51

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Same comment for icon. Check also Travis errors.

**Comment by llacroix** [comment]
Depends on 
* [ ]  #27 
* [ ] #51 
* [ ] #17 
* [ ] #52

**Comment by dreispt** [comment]
Waiting on dependencies.

**Comment by max3903** [comment]
:+1:

**Comment by dreispt** [comment]
:+1:

**Pull request merged**
