### PR TITLE
8.0 document page health safety manual

### PR DESCRIPTION
**Pull request by max3903**
Depends on:
- [x] #23

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Check icon and Travis.

**Comment by max3903** [comment]
@llacroix can you add the README.rst from the template and fix Travis errors please ?

**Comment by llacroix** [comment]
Depends on https://github.com/OCA/management-system/pull/23 [mgmtsystem_manuals]

**Comment by dreispt** [comment]
:+1:

**Comment by max3903** [comment]
Tested on runbot

:+1:

**Pull request merged**
