### PR TITLE
10.0 mig mgmtsystem hazard risk

### PR DESCRIPTION
**Pull request by ngrandjean**
Module depends on mgmtsystem_hazard

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please squash together adjacent "OCA Transbot.." commits using https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests.

Have you signed the CLA? https://odoo-community.org/page/cla

And check also Travis status.

**Comment by ngrandjean** [comment]
@pedrobaeza Thanks for the review. I squashed OCA transbot commits (it's the first time I do that so I hope it's correct) and fixed the issues.
I signed the CLA last year, I guess it's still valid ?

**Comment by max3903** [comment]
@ngrandjean There are 2 modules in your pull request. Please split it.

**Comment by ngrandjean** [comment]
Hello,

Sorry for the delay. I actually made a mess trying to squash commits and starting branch from branch "10.0-mig-mgmtsystem_hazard" so I think it would be much easier if I'd just close this PR and make another one correctly.

**Pull request closed without merging**
