### PR TITLE
Fix 'singleton expexted error' on _compute_risk method

### PR DESCRIPTION
**Pull request by Odew**

### CODE REVIEW

**Comment by max3903** [comment]
@Odew Thanks! Can you fix the flake8 errors below please?

```
mgmtsystem_hazard_risk/models/mgmtsystem_hazard.py:45:80: E501 line too long (80 > 79 characters)
mgmtsystem_hazard_risk/models/mgmtsystem_hazard.py:51:18: W291 trailing whitespace
```

**Comment by dreispt** [comment]
This is a reminder to us that we should start be picking more about PR code test coverage...

**Comment by Odew** [comment]
Hello, just for my personal knowledge, what coverage/coveralls does and how to success the checks ?

**Comment by max3903** [comment]
@Odew Coveralls compute the percentage of your code used during the execution of your tests. 

If you create new tests which will execute lines of your code that were not executed before by the previous tests, the code coverage will increase.

If you have new lines of code without tests running them, the code coverage will decrease.

For example, in this file: https://coveralls.io/builds/4338713/source?filename=mgmtsystem_hazard_risk%2Fmodels%2Fmgmtsystem_hazard.py
lines in green are tested, those in red are not.

**Comment by Odew** [comment]
Hi all, do i need to do something else to validate this pull request ?

**Comment by max3903** [comment]
@odew No, you are done. Thanks. I will do my best to review it later today.

**Comment by Odew** [comment]
@max3903 ok thanks

**Comment by dreispt** [comment]
LGTM :+1:

**Comment by max3903** [comment]
:+1:

**Pull request merged**
