### PR TITLE
[MIG][13.0] mgmtsystem_action_template

### PR DESCRIPTION
**Pull request by mymage**
Migration to 13.0

### CODE REVIEW

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Review by ivantodorovich — APPROVED** [review]

**Comment by ivantodorovich** [comment]
@mymage the merge cmd has failed. The error seems unrelated though, could you try a rebase to see if it's solved?

**Comment by mymage** [comment]
> @mymage the merge cmd has failed. The error seems unrelated though, could you try a rebase to see if it's solved?

I think that Travis has some problem.

**Comment by ivantodorovich** [comment]
> I think that Travis has some problem.

We should probably switch to github actions anyway, doing a new project template update with `copier`
That would probably solve the issue

**Comment by ivantodorovich** [comment]
@mymage I believe it's only pre-commit that's failing now :)
if you fix it we can merge

**Comment by mymage** [comment]
> @mymage I believe it's only pre-commit that's failing now :) if you fix it we can merge

I think that codecov can be forced right?

**Comment by ivantodorovich** [comment]
Yes :) it's fine now. Thanks!!

/ocabot merge nobump

**Pull request merged**
