### PR TITLE
[12.0][ADD] mgmtsystem_nonconformity_fieldservice

### PR DESCRIPTION
**Pull request by marcelsavegnago**
Add module mgmtsystem_nonconformity_fieldservice

### CODE REVIEW

**Comment by etobella** [comment]
Just a question, this module depends on `fieldservice` that is somehow a vertical, shouldn't this module be there?

**Comment by marcelsavegnago** [comment]
> Just a question, this module depends on `fieldservice` that is somehow a vertical, shouldn't this module be there?

@etobella I honestly believed it could be here. But without a problem, I can do it directly in the OCA/field-service project. Do you think better?. Management System is a vertical one too, isn't it?

**Comment by etobella** [comment]
I know that could be in both sides, but I think that the good one is `fieldservice` because there is already accounting, stock and much more repos. IMO, `fieldservice` is a vertical and all the related modules needs to be directly there

Also, Management system is not a vertical, as it only manages an aspect that a lot of companies need to fulfill, from all sectors, `fieldservice` is for just some kind of companies, that's why I say it is a vertical (or at least, similar)

**Comment by marcelsavegnago** [comment]
> I know that could be in both sides, but I think that the good one is `fieldservice` because there is already accounting, stock and much more repos. IMO, `fieldservice` is a vertical and all the related modules needs to be directly there

Ok I'll change and submit to the Field Service repository. Thanks for your help and explanation.

**Comment by marcelsavegnago** [comment]
> I know that could be in both sides, but I think that the good one is `fieldservice` because there is already accounting, stock and much more repos. IMO, `fieldservice` is a vertical and all the related modules needs to be directly there
> 
> Also, Management system is not a vertical, as it only manages an aspect that a lot of companies need to fulfill, from all sectors, `fieldservice` is for just some kind of companies, that's why I say it is a vertical (or at least, similar)

@etobella https://github.com/OCA/field-service/pull/585

**Pull request closed without merging**
