### PR TITLE
[17.0] [MIG] document_page_work_instruction

### PR DESCRIPTION
**Pull request by ThinkopenDev**
Straightforward migration from 16.0

### CODE REVIEW

**Comment by mymage** [comment]
@ThinkopenDev please re-push so runboat will go green.

**Comment by ThinkopenDev** [comment]
Sorry, closed PR on accident.

**Review by mymage — APPROVED** [review]
LGTM. If you can, allign the title with the standard, thanks

**Comment by mymage** [comment]
While testing on Runboat I realize that the behavior is not the one described in the readme: the Categories item does not appear in the Configuration menu.
The entry is probably added from another module.
In this case for me it is better to change the readme. I don't know if it will be correct to add that module as a dependency.
If anyone has the time and knowledge to check, they are welcome.

**Comment by mymage** [comment]
Hi @ThinkopenDev, the repo was fixed (see #585).
Then I think you have to re-push this after a rebase. Thanks!

**Review by max3903 — APPROVED** [review]

**Pull request merged**
