### PR TITLE
[11.0] [ADD] new module mgmtsystem_action_efficacy

### PR DESCRIPTION
**Pull request by mymage**
Ref. #263

### CODE REVIEW

**Review by marcelofrare — APPROVED** [review]
functionally it is ok for me

**Review by marcelsavegnago — APPROVED** [review]

**Comment by mymage** [comment]
@dreispt Hi, can I do something to pass checks? Maybe add test?

**Comment by dreispt** [comment]
@mymage The issue is shown in the TravisCI build log, here: https://travis-ci.com/github/OCA/management-system/jobs/453597378#L296

Change the development_status to `Beta`

**Review by etobella — APPROVED** [review]

**Pull request merged**
