### PR TITLE
[FIX] missing compute

### LINKED ISSUE #317: Missing compute function `_compute_number_of_days_to_close`
https://github.com/OCA/management-system/blob/b1c11b93d9b9fb253ae2976cf5269afa2dd775d0/mgmtsystem_nonconformity/models/mgmtsystem_nonconformity.py#L46

### PR DESCRIPTION
**Pull request by sergiocorato**
Closes #317

### CODE REVIEW

**Review by ivantodorovich — APPROVED** [review]

**Review by dreispt — APPROVED** [review]

**Comment by dreispt** [comment]
Should this be forward ported to v13?

**Comment by sergiocorato** [comment]
> Should this be forward ported to v13?

yes

**Comment by sergiocorato** [comment]
#322

**Pull request merged**
