### PR TITLE
[MIG] Enterprise-like icon & set management-system as a fully-fledge application

### PR DESCRIPTION
**Pull request by ivantodorovich**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Master file is SVG? It would be good to include it also here.

**Comment by ivantodorovich** [comment]
It's an Adobe Illustrator file (.ai), but it can be easily exported to SVG.

Where should I place it?

**Comment by pedrobaeza** [comment]
In the same folder as the PNG (/src/description).

**Comment by ivantodorovich** [comment]
Done!

**Review by pedrobaeza — APPROVED** [review]

**Review by etobella — APPROVED** [review]
LGTM :+1:

**Pull request merged**
