### PR TITLE
[14.0][MIG] mgmtsystem action efficacy

### PR DESCRIPTION
**Pull request by mymage**
Migration to 14.0

### CODE REVIEW

**Comment by mymage** [comment]
@max3903 Hi, can you help me to understand/fix the pre-commit errors? For what I see it's not on my code. Thanks

**Comment by max3903** [comment]
@mymage It's an issue with the newly released Python 3.11. Here is the fix:
https://github.com/OCA/field-service/commit/0f0d0f06f42eee83cf68f790dd131f1010b487b0

**Comment by mymage** [comment]
> @mymage It's an issue with the newly released Python 3.11. Here is the fix: [OCA/field-service@0f0d0f0](https://github.com/OCA/field-service/commit/0f0d0f06f42eee83cf68f790dd131f1010b487b0)

Thanks for the info. Now it works.

**Comment by mymage** [comment]
@max3903 do you think that is better to create a dedicated PR for the pre-commit fix and rebase this, because there are other PRs waiting so rebasing on a fixed 14.0 will be better.

**Review by max3903 — APPROVED** [review]

**Comment by max3903** [comment]
@mymage The other PRs can be rebased once this one is merged.

**Pull request merged**
