### PR TITLE
[IMP] mgmtsystem_action

### PR DESCRIPTION
**Pull request by ivantodorovich**
**[IMP] Improved Actions Kanban, added Action Tags**

- Added "My Actions" filter, and improved action
- Added Activities mixing
- Improved kanban views and filters
- Add sequence and priority to actions
- Change description field from Text to HTML to allow formatting in description

**[IMP] Improvements in Action Stages**

- Add description field to stages
- Add fold field to stages (Folded state in kanbas)
- Remove unused field case_default

**[REF] Cleanup Action Workflow code**

- Refactored old workflow code that was unused or didn't make any sense with the new action.stage

**[FIX] Unable to modify Action Stages (and Tags)**

- Fixes 'Unable to modify Stages without admin' (and the same for Tags)

**[MIG] Remove old migration scripts**

- Removed migration scripts from previous odoo versions

**[MIG] FIX Migration of ir.cron**

- Fixed migration of ir.cron

``` 
2018-10-25 22:43:36,643 171 INFO openerp_test odoo.modules.loading: loading mgmtsystem_action/data/automated_reminder.xml
2018-10-25 22:43:36,683 171 WARNING openerp_test odoo.models: ir.cron.create() includes unknown fields: function, model
```

### CODE REVIEW

**Review by max3903 — APPROVED** [review]
LGTM

**Comment by ivantodorovich** [comment]
@max3903 I've pushed 2 more commits. I've refactored the old workflow code. There was unused stuff from when we didn't have `mgmtsystem.action.stage`

**Comment by max3903** [comment]
Fixes #208 and #225

**Comment by ivantodorovich** [comment]
@jalzaga would you be so kind to review this? 🙏

**Comment by ivantodorovich** [comment]
I've pushed a new commit that fixes a migration error in the ir.cron job, also making runbot happy.
Giving that it's almost a month old, and it fixes some bugs, should we merge this? Or should be wait for more reviewers?

**Pull request merged**
