### PR TITLE
Update project meta files

### LINKED ISSUE #5: 7.0 Travis fail - missing dependency 'document_page_approval'
except_orm: (u'Error', u"You try to install module 'document_page_environmental_aspect' that depends on module 'document_page_approval'.\nBut the latter module is not available in your system.")

### PR DESCRIPTION
**Pull request by bwrsandman**
Fixes #5

### CODE REVIEW

**Comment by rvalyi** [comment]
:+1: LGTM

**Comment by pedrobaeza** [comment]
It still has the same error...

**Comment by bwrsandman** [comment]
So many dependencies...

**Comment by pedrobaeza** [comment]
Now the error is:

```
except_orm: (u'Error', u"You try to install module 'mgmtsystem_kpi' that depends on module 'web_color'.\nBut the latter module is not available in your system.")
```

**Comment by bwrsandman** [comment]
@pedrobaeza on it

**Comment by pedrobaeza** [comment]
I have seen it late :wink:

**Comment by bwrsandman** [comment]
This new error is odd...

**Comment by rvalyi** [comment]
hey no dependency manager; but we've got apps.odoo.com !
;-p

**Comment by bwrsandman** [comment]
Tries to send an email when installing to demo data...

Any clues as to how to avoid this?

**Comment by pedrobaeza** [comment]
Seems that XML ID for admin is not base.user_root, and it's referenced on `/home/travis/build/OCA/management-system/mgmtsystem_action/demo_action.xml`. You can comment that demo data or try to see what ref to put.

**Comment by bwrsandman** [comment]
@pedrobaeza `base.user_root` is correct. The problem is the creation of an action sends an email

**Comment by rvalyi** [comment]
:+1: LGTM

**Comment by pedrobaeza** [comment]
This one is still resisting... Might we leave it for another PR?

**Comment by bwrsandman** [comment]
Error should be fixed, only pep8 failing and that's solved in #7

**Comment by pedrobaeza** [comment]
:+1: Thanks for the effort

**Comment by gurneyalex** [comment]
:+1:

**Pull request merged**
