### PR TITLE
[13.0] [MIG] mgmtsystem_nonconformity_mrp

### PR DESCRIPTION
**Pull request by mymage**
Depends on #375

### CODE REVIEW

**Comment by mymage** [comment]
At the moment I'm not able to solve the problem with Travis (a pylint incompatibility in pre-commit). Any suggestion is wellcome.

**Review by dreispt — APPROVED** [review]

**Review by ivantodorovich — APPROVED** [review]

**Comment by ivantodorovich** [comment]
@mymage CI is failing due to pre-commit, would you check it out?

**Comment by mymage** [comment]
@ivantodorovich Yes sure, I have only to fix a problem with my configuration because pre-commit falls with the message 
```
The conflict is caused by:
        pre-commit-dummy-package 0.0.0 depends on pylint==2.3.1
        pylint-odoo 3.0.3 depends on pylint==2.3.0
```

**Comment by mymage** [comment]
@ivantodorovich can you plase give a look at #335 ? I don't know if and how to fix it. Thanks

**Review by andreampiovesana — APPROVED** [review]
go

**Pull request merged**
