### PR TITLE
[13.0][MIG] document_page_quality_manual: Migration to 13.0

### PR DESCRIPTION
**Pull request by ernestotejeda**
Cc @Tecnativa TT20477

### CODE REVIEW

**Comment by ernestotejeda** [comment]
I reduced the commit history a bit

**Comment by ernestotejeda** [comment]
I have removed the **mgmtsystem_manual** dependency because this module does not use any features or alters any resources from **mgmtsystem_manual**. I don't know if there is any other reason I am missing that I need to maintain that dependence.
Technically it only depends on **document_page**
ping @pedrobaeza .

**Comment by pedrobaeza** [comment]
If no technical dependency, then better to not force it.

**Review by Tardo — APPROVED** [review]
:+1: LGTM

** Update oca_dependencies when ready

**Comment by ernestotejeda** [comment]
oca_dependencies.txt file updated

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
