### PR TITLE
Add Codacy code quality badge

### PR DESCRIPTION
**Pull request by dreispt**

### CODE REVIEW

**Comment by bwrsandman** [comment]
Pretty cool :+1:

**Comment by dreispt** [comment]
I just contacted Codacy support, and they confirmed it's free for open source projects.

**Comment by pedrobaeza** [comment]
Seems good, but what are the parameters to measure that quality?

**Comment by dreispt** [comment]
@pedrobaeza What do you mean?

**Comment by pedrobaeza** [comment]
Codacy put A, B, C... as certification lvel, but how it grant that level?

**Comment by dreispt** [comment]
These are the details available: https://www.codacy.com/docs?page=grade
Maybe it's based on a ratio of issues per line.
landspace.io uses a percentage instead, but that ends up with a similar question.

I wonder if it would be worth building our own custom warning/grading logic, outputting to the log?

**Comment by pedrobaeza** [comment]
Yeah, it seems that "industry standards" is a little fuzzy to determine the quality of Odoo code. We should investigate a way to get a custom grading logic as you mention.

**Comment by dreispt** [comment]
Merge?

**Comment by pedrobaeza** [comment]
OK :+1:

**Pull request merged**
