### PR TITLE
Add meta files

### PR DESCRIPTION
**Pull request by bwrsandman**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Could you please add on README an extended description of the purpose of the repository?

**Comment by bwrsandman** [comment]
@pedrobaeza Done! Good catch.

**Comment by bwrsandman** [comment]
Why does the test pass if there are flake8 errors?

**Comment by pedrobaeza** [comment]
Maybe a problem in the Travis script?

A travis.yml in another repository contains:

```
- flake8 . --max-line-length=120 --filename=__init__.py --ignore=F401
- flake8 . --max-line-length=120 --exclude=__init__.py
```

Regards.

**Comment by bwrsandman** [comment]
@pedrobaeza https://github.com/OCA/maintainer-quality-tools/pull/26

**Pull request merged**
