### PR TITLE
[11.0][MIG] mgmtsystem

### PR DESCRIPTION
**Pull request by jalzaga**
Module mgmtsystem Migration to version 11.0 #200

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please squash together adjacent "Launchpad automatic translations update." commits using https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests

**Comment by jalzaga** [comment]
OK Pedro

**Review by max3903 — APPROVED** [review]
:+1: Thank you!

**Review by etobella — CHANGES_REQUESTED** [review]
LGTM :+1:

**Review by etobella — APPROVED** [review]
LGTM

**Review by GavyMG — APPROVED** [review]

**Pull request merged**
