### PR TITLE
[11.0][MIG] mgmtsystem action

### PR DESCRIPTION
**Pull request by jalzaga**
Module mgmtsystem_action Migration to version 11.0 #200

### CODE REVIEW

**Comment by GavyMG** [comment]
@jalzaga 

could you continue this PR?
mgmtsystem module is merged already.

**Comment by max3903** [comment]
@jalzaga Please rebase your branch on OCA/11.0

**Comment by etobella** [comment]
Something is weird with the commit history... I mean, the commits of the 11.0, shouldn't be referenced on the PR, but I can see this commits on the PR. How did you rebase?

**Comment by ivantodorovich** [comment]
@jalzaga what's the status on this? 
I need this module and I'm unsure whether to pick up on your work or make a new migration

**Comment by jalzaga** [comment]
@max3903 Could you please tell me what is the problem with this PR.

**Review by max3903 — APPROVED** [review]

**Review by ivantodorovich — APPROVED** [review]
Runbot is failing but it seems unrelated to this PR.
Maybe try doing a force push to rerun it?

**Pull request merged**
