### PR TITLE
move icon.png to mgmtsystem/static/description/

### PR DESCRIPTION
**Pull request by gborelli**
1. Moved icon.png to /static/description folder  as described there: https://github.com/OCA/management-system/issues/49
2. Added .gitignore file

### CODE REVIEW

**Comment by pedrobaeza** [comment]
You can remove also .bzrignore.

**Comment by pedrobaeza** [comment]
BTW, :+1:

**Comment by dreispt** [comment]
:+1:

**Comment by bwrsandman** [comment]
:+1:

**Pull request merged**
