### PR TITLE
[MIG][17.0] mgmtsystem_nonconformity

### PR DESCRIPTION
**Pull request by EdgarRetes**

### CODE REVIEW

**Comment by bosd** [comment]
Thanks for this migration.
There are some warnings in the test log. Can you please attend to them?

**Comment by peluko00** [comment]
Can you merge migration commits into one please @EdgarRetes

**Comment by EdgarRetes** [comment]
> Can you merge migration commits into one please @EdgarRetes

Done!

**Review by mymage — CHANGES_REQUESTED** [review]
Hi @EdgarRetes, I did a test on runboat and found some issues.
In particular for me there are some errors in nonconformity view migration for example on the invisibility rule for Actions and Causes and Analysis, where `attrs="{'invisible':[('state','in',['draft','cancel'])]}"` is refactored as `invisible="state not in 'draft' and state not in 'cancel'"`.
I changed the code on the fly in runboat and it allows me to go further with state change (after filling the required fields).
Please let me know if I'm wrong and if I can help in some way.

**Comment by EdgarRetes** [comment]
> Hi @EdgarRetes, I did a test on runboat and found some issues. In particular for me there are some errors in nonconformity view migration for example on the invisibility rule for Actions and Causes and Analysis, where `attrs="{'invisible':[('state','in',['draft','cancel'])]}"` is refactored as `invisible="state not in 'draft' and state not in 'cancel'"`. I changed the code on the fly in runboat and it allows me to go further with state change (after filling the required fields). Please let me know if I'm wrong and if I can help in some way.

You are right, I had them wrong. Thanks for your comment! Let me know if you have some other erros

**Comment by mymage** [comment]
> You are right, I had them wrong. Thanks for your comment! Let me know if you have some other erros

I don't know if it's my problem, but I don't see the runboat link to test it. Maybe you need to push again to update the generation? Thanks

**Comment by EdgarRetes** [comment]
> > You are right, I had them wrong. Thanks for your comment! Let me know if you have some other erros
> 
> I don't know if it's my problem, but I don't see the runboat link to test it. Maybe you need to push again to update the generation? Thanks

I just pushed it again for you to test it

**Comment by EdgarRetes** [comment]
> > You are right, I had them wrong. Thanks for your comment! Let me know if you have some other erros
> 
> I don't know if it's my problem, but I don't see the runboat link to test it. Maybe you need to push again to update the generation? Thanks

I just pushed it again

**Review by mymage — APPROVED** [review]
Positive test on runboat

**Review by max3903 — APPROVED** [review]

**Pull request merged**
