### PR TITLE
[17.0] [MIG] mgmtsystem_audit

### PR DESCRIPTION
**Pull request by m1k3lm**
/ocabot migration mgmtsystem_audit

### CODE REVIEW

**Comment by mymage** [comment]
@m1k3lm please re-push to check test now

**Comment by m1k3lm** [comment]
@mymage Done!

**Comment by mymage** [comment]
> @mymage Done!

Thanks, it looks good but please, as I sed on the issue #554 and indicate here https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0, do a PR for each single module. 
It is a bit boring but it contributes to manage code better.
Thanks!

**Review by dreispt — CHANGES_REQUESTED** [review]
This should have only files for the `mgmtsystem_audit` module

**Comment by mymage** [comment]
Hi @m1k3lm, the repo was fixed (see #585).
Then I think you have to update your code before do the single PR.
Since I think the code for each module is good, if you want I can help you doing PRs for specific modules using your code: let me know which one.
Thanks!

**Comment by m1k3lm** [comment]
@mymage created separate PR for mgmtsystem_action #589 and mgmtsystem_audit #590

**Comment by mymage** [comment]
> @mymage created separate PR for mgmtsystem_action #589 and mgmtsystem_audit #590

@m1k3lm Thanks: remembe to indicate it on #554

**Pull request closed without merging**
