### PR TITLE
[12.0] [ADD] new module mgmtsystem_partner

### PR DESCRIPTION
**Pull request by mymage**
This is the migration of #286 still waiting review: I hope it can have more audience on this version :-)
Ref. #263

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
I don't know what the effort would be, but it may be more interesting to reuse the contact register by creating a new type called Quality. What do you think ?

https://github.com/odoo/odoo/blob/39dbc8b0935a44c3457938076ff5688fc0800414/odoo/addons/base/models/res_partner.py#L180

image

**Comment by mymage** [comment]
> I don't know what the effort would be, but it may be more interesting to reuse the contact register by creating a new type called Quality. What do you think ?

I think You are right. Let me some time to refactor the logic (there is another PR module connected #284).

**Comment by mymage** [comment]
@marcelsavegnago Updated with your suggestion.

**Review by marcelsavegnago — APPROVED** [review]

**Comment by mymage** [comment]
@marcelofrare @primes2h @sergiocorato please review

**Comment by marcelsavegnago** [comment]
@eduaparicio please review

**Comment by mymage** [comment]
I received a suggestion to use a "standard way" to manage the lack of the quality contact email (that I manage with dedicated code). 
This standard way is used for example when you try to send an invoice via email and the Invoice Contact hasn't the email set.
Someone know if and how this can be implemented?

**Comment by mymage** [comment]
@marcelofrare @primes2h please review

**Comment by mymage** [comment]
Following some comment on #286 I slightly changed the module, basically the name, opening it to implementation for other systems.

**Review by primes2h — APPROVED** [review]
LGTM :+1:

**Review by marcelofrare — APPROVED** [review]
LGTM

**Review by etobella — APPROVED** [review]

**Review by ivantodorovich — APPROVED** [review]

**Pull request merged**
