### PR TITLE
7.0 mgmtsystem nonconformity field name

### PR DESCRIPTION
**Pull request by foutoucour**
Add the field name to nonconformities.
The name is also used to replace the description in the header of the form view.

### CODE REVIEW

**Comment by max3903** [comment]
:-1: 

Just add the field in the current module

**Comment by bwrsandman** [comment]
A whole module for a fix to nonconformity is probably overkill.

I should assume that these are fixes would benefit everyone using nonconformity.

It's probably better to update the existing module directly.

**Comment by dreispt** [comment]
Isn't this solving the same thing as #38?
I suggest doing only one PR for these.

**Comment by foutoucour** [comment]
Merging the update in the mgmsystem_nonconformity as suggested.

**Pull request closed without merging**
