### PR TITLE
[7.0][FIX] Flake8 errors W503 [needs review]

### PR DESCRIPTION
**Pull request by llacroix**
These errors prevent some travis tests to pass.

### CODE REVIEW

**Comment by llacroix** [comment]
Runbot doesn't have server-tools

**Comment by yvaucher** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by veloutin** [comment]
:+1:

**Comment by llacroix** [comment]
Thanks is it possible to restart the build for #46  and #47  ?

**Comment by pedrobaeza** [comment]
You will have to rebase.

**Comment by llacroix** [comment]
Ok I can rebase both branches, tests are passing except of runbot

**Comment by pedrobaeza** [comment]
Then there's no problem, as runbot is not working properly for now.

**Pull request merged**
