### PR TITLE
[FIX] mgmtsystem_audit: number_of_nonconformities

### PR DESCRIPTION
**Pull request by diggy128**
Since iterating over self, nonconformities should be calculated over audit

### CODE REVIEW

**Comment by diggy128** [comment]
@ivantodorovich 
Done

**Review by ivantodorovich — APPROVED** [review]
Thanks!!

**Review by max3903 — APPROVED** [review]

**Comment by max3903** [comment]
Ping @flachica

**Comment by flachica** [comment]
Resolved on #309

**Pull request merged**
