### PR TITLE
Add OCA dependencies

### PR DESCRIPTION
**Pull request by dreispt**

### CODE REVIEW

**Comment by max3903** [comment]
We also need:
- server-tools for external_dbsource module
- web for web_color or web_widget_color

used in mgmtsystem_kpi.

**Comment by dreispt** [comment]
Added.

**Comment by max3903** [comment]
:+1:

**Comment by yvaucher** [comment]
You might need to remove dependencies from travis

```
The command "git clone https://github.com/OCA/knowledge.git -b ${VERSION} $HOME/knowledge" failed and exited with 128 during .
```

**Comment by dreispt** [comment]
@yvaucher I was in doubt since that was not done in other repos, but I agree and it's done.

**Comment by max3903** [comment]
:+1:

**Comment by yvaucher** [comment]
@dreispt and it's green :+1:

**Comment by yvaucher** [comment]
sorry I merged it a bit fast I was certain there was 2 other people with thumps up.

#seeing_double #end_of_day

**Pull request merged**
