### PR TITLE
[16.0][ADD] mgmtsystem_nonconformity_maintenance_equipment: add new module

### PR DESCRIPTION
**Pull request by kaynnan**
cc @marcelsavegnago @douglascstd

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
cc @WesleyOliveira98

**Review by WesleyOliveira98 — APPROVED** [review]
LGTM

**Review by marcelsavegnago — APPROVED** [review]

**Comment by kaynnan** [comment]
ping @OCA/management-systems-maintainers

**Comment by kaynnan** [comment]
ping @OCA/management-systems-maintainers

**Review by dreispt — APPROVED** [review]

**Pull request merged**
