### PR TITLE
[FIX] formating non_conformity form view

### PR DESCRIPTION
**Pull request by ghost**
Fix the separator which shifts groups and fields below it when it is visible.
Before:
mgmtsystem_nonconformity
After:
mgmtsystem_nonconformity_fix

### CODE REVIEW

**Comment by dreispt** [comment]
Great "before" and "after".
One suggestion: remove the label from the "Evaluation Comments" and instead use a `placeholder` text on it.

**Comment by max3903** [comment]
@lgkodw Thanks for the contribution. Can you apply @dreispt's suggestion to Action Plan Comments as well ?

Otherwise :+1:

**Comment by dreispt** [comment]
@lgkodw Did you sign the CLA?

**Comment by ghost** [comment]
@max3903 I can, just need a few time 
@dreispt not yet

**Comment by ghost** [comment]
I close this pull request with this company github account.
I reopen the pull request with my personal github account which is linked with the CLA document.

**Pull request closed without merging**
