### PR TITLE
- fix 'Effectiveness Review' group on nonconformity form view

### PR DESCRIPTION
**Pull request by Odew**
Fix the 'Effectiveness Review' group

Before:
mgmtsystem_nonconformity

After:
mgmtsystem_nonconformity_fix

This is a reopen pull request with my personal github account linked in the CLA document

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by max3903** [comment]
Thanks @Odew . Can you do the same to the Action Plan comments field please?

and move the description in README.rst:
https://travis-ci.org/OCA/management-system/jobs/95601910#L385

otherwise :+1:

**Comment by Odew** [comment]
@max3903 fixed ;)

**Comment by max3903** [comment]
@Odew Awesome!

**Comment by dreispt** [comment]
:+1: Thanks!

**Pull request merged**
