### PR TITLE
[12.0] [ADD] new module mgmtsystem_action_efficacy

### PR DESCRIPTION
**Pull request by mymage**
This is the migration of #283 still waiting review: I hope it can have more audience on this version :-)
Ref. #263

### CODE REVIEW

**Comment by mymage** [comment]
@marcelofrare @primes2h @sergiocorato please review

**Review by marcelofrare — APPROVED** [review]
functionally it is ok for me

**Review by marcelsavegnago — APPROVED** [review]
Its ok for me

**Pull request merged**
