### PR TITLE
[13.0][MIG] document_page_environment_manual

### PR DESCRIPTION
**Pull request by flachica**
Many conflicts on git format-patch. This PR solve #302 problems

### CODE REVIEW

**Review by dreispt — APPROVED** [review]

**Comment by Rad0van** [comment]
When will this be merged? #303 is failing on this being missing. I can volunteer to do some stuff if needed.

**Comment by flachica** [comment]
I have migrated all the modules I was missing to version 13.0. Use this repository https://github.com/flachica/management-system and the branchs in case it helps you. On some occasion I had problems with the git rebase but all the code is working in my test environment

**Comment by Rad0van** [comment]
> I have migrated all the modules I was missing to version 13.0. Use this repository https://github.com/flachica/management-system and the branchs in case it helps you. On some occasion I had problems with the git rebase but all the code is working in my test environment

Thanx for info. I'll wait a bit I guess to see if this gets going on.

**Review by ivantodorovich — APPROVED** [review]

**Comment by flachica** [comment]
> @ivantodorovich your merge command was aborted due to failed check(s), which you can inspect on [this commit of 13.0-ocabot-merge-pr-324-by-ivantodorovich-bump-nobump](https://github.com/OCA/management-system/commits/3e13ad5f057865d76aebba3173bc66672367ae05).
> 
> After fixing the problem, you can re-issue a merge command. Please refrain from merging manually as it will most probably make the target branch red.

@ivantodorovich This error is new for me. Flake8 don't understand a correct sentence in my opinion

**Comment by ivantodorovich** [comment]
Can you rebase on 13.0 ?
Maybe there where changes in precommit that are not in this branch

**Comment by flachica** [comment]
@ivantodorovich  Of course, the rebase was initiated 15 minutes ago [here](https://github.com/OCA/management-system/pull/324/commits/9f5ab79179ebe7a152b40ae0ef66b122c0e0ea41)

**Comment by Rad0van** [comment]
> @ivantodorovich Of course, the rebase was initiated 15 minutes ago [here](https://github.com/OCA/management-system/pull/324/commits/9f5ab79179ebe7a152b40ae0ef66b122c0e0ea41)

How is this going? Can I help with anything?

**Comment by ivantodorovich** [comment]
All clear, just please squash `Flake8 error` commit into the `Migration to 13.0` commit, and that's it :)

**Comment by Rad0van** [comment]
I guess only @flachica can do that, right?

**Comment by flachica** [comment]
@Rad0van @ivantodorovich It is done

**Comment by Rad0van** [comment]
> @Rad0van @ivantodorovich It is done

Fantastic! Thank you. Will this be merged automatically or someone has to to sign it off?
Now we can progress with #303

**Pull request merged**
