### PR TITLE
[ADD] mgmtsystem_nonconformity: Add activities to nonconformity

### PR DESCRIPTION
**Pull request by nicomacr**
Add the activities to the model "nonconformity"

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by max3903 — APPROVED** [review]

**Review by zaoral — APPROVED** [review]
+1 

Excellent @nicomacr! thank for the change.
NOTE: Please if you can add it also to the kanban view

**Review by ivantodorovich — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@nicomacr now there's no need of bumping manually version number, as the bot does it for us.

/ocabot merge

**Comment by pedrobaeza** [comment]
please forward port this to 12.0

**Comment by nicomacr** [comment]
thanks @pedrobaeza 
The port to 12.0 is in this PR #260

**Pull request closed without merging**
