### PR TITLE
[12.0] [ADD] new module mgmtsystem_nonconformity_type

### PR DESCRIPTION
**Pull request by mymage**
This is the migration of #284 still waiting review: I hope it can have more audience on this version :-)
This module requires #348
Ref. #263

### CODE REVIEW

**Comment by mymage** [comment]
@marcelsavegnago @marcelofrare @primes2h @sergiocorato please review

**Review by marcelofrare — APPROVED** [review]
functionally is ok for me. Thanks @mymage !

**Review by ivantodorovich — APPROVED** [review]

**Comment by marcelsavegnago** [comment]
@mymage Can you do a rebase?

**Comment by mymage** [comment]
> @mymage Can you do a rebase?

I did it but I don't know how to solve errors.

**Pull request merged**
