### PR TITLE
15.0 mig document page procedure

### PR DESCRIPTION
**Pull request by YvanDotet**

### CODE REVIEW

**Review by ivantodorovich — APPROVED** [review]

**Comment by YvanDotet** [comment]
@ivantodorovich 
Thank you

**Review by ivantodorovich — APPROVED** [review]

**Comment by YvanDotet** [comment]
@ivantodorovich 
Hello,
is the last fail for build is important for the merging ?

Thank you.

**Comment by ivantodorovich** [comment]
> @ivantodorovich Hello, is the last fail for build is important for the merging ?
> 
> Thank you.

Do you mean codecov/project ? 
No, we can merge without it :)

**Comment by YvanDotet** [comment]
@ivantodorovich 
Ok nice I think it will be ok for merging.
Perhaps someone else is needed for the validation ?

Thanks.

**Review by ivantodorovich — APPROVED** [review]

**Comment by ivantodorovich** [comment]
normally we'd need 2 approvals, but let's fast-track it on the account it's a standard migration and not so frequented repo 😅 

/ocabot merge nobump

**Comment by yankinmax** [comment]
@YvanDotet maybe you have to regenerate `setup`. Pls run `pre-commit run -a` again.

**Comment by YvanDotet** [comment]
> @YvanDotet maybe you have to regenerate `setup`. Pls run `pre-commit run -a` again.

@yankinmax 
Ok thanks it's work.

**Comment by YvanDotet** [comment]
@ivantodorovich 
@yankinmax 
Thank you to you.

**Pull request merged**
