### PR TITLE
Fix check recursion

### PR DESCRIPTION
**Pull request by bwrsandman**
Made a typo when I fixed pep8 and went to use the base _check_recursion.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by bwrsandman** [comment]
@rvalyi @gurneyalex This fixes an error introduced in #7 (pep8 fix on project)

**Comment by joaoalf** [comment]
:+1:
LGTM

**Comment by max3903** [comment]
:+1:

**Comment by rvalyi** [comment]
:+1:  LGTM we won't lint all repos at larges without having a regression or two sadly.

**Pull request merged**
