### PR TITLE
[REF] 8.0 mgmtsystem quality

### PR DESCRIPTION
**Pull request by llacroix**
Marked as installable no change required depends on 3 other modules
- [x] #27 
- [x] #50 
- [x] #51

### CODE REVIEW

**Comment by bwrsandman** [comment]
Please rename `quality.xml` to `mgmtsystem_system_data.xml`

**Comment by bwrsandman** [comment]
depends on #27

**Comment by dreispt** [comment]
:+1:

**Comment by bwrsandman** [comment]
Needs a rebase

**Comment by llacroix** [comment]
@bwrsandman I'm aware but dependencies aren't yet done so it can wait a little.

**Comment by max3903** [comment]
:+1:

**Pull request merged**
