### PR TITLE
12.0 mgmtsystem nonconformity

### PR DESCRIPTION
**Pull request by gurneyalex**
depends on:

- [x] #244 
- [x] document_page_procedure #250

### CODE REVIEW

**Comment by i-vyshnevska** [comment]
@gurneyalex  depends on not migrated document_page_procedure

**Comment by i-vyshnevska** [comment]
@gurneyalex document_page_procedure migrated https://github.com/OCA/management-system/pull/250
I will pick up your PR to finish migration

**Comment by max3903** [comment]
Still WIP?

**Comment by ernestotejeda** [comment]
I've done this PR (https://github.com/OCA/management-system/pull/256) that solves an error in mgmtsystem_action that causes this PR to fail. check it out, please. This PR is needed for https://github.com/OCA/management-system/pull/257

**Comment by pedrobaeza** [comment]
Rebased after making Travis green and rebased for reducing the huge useless commit history. There were already conflicts that wasn't correctly fixed in 11.0 migration, but I haven't touched that as it's too complicated to solve them now.

**Review by ernestotejeda — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
