### PR TITLE
15.0 mig mgmtsystem

### PR DESCRIPTION
**Pull request by YvanDotet**

### CODE REVIEW

**Comment by etobella** [comment]
Precommit is failing

**Comment by YvanDotet** [comment]
@etobella 
Ok it's green now. It misses the setup file.

**Comment by YvanDotet** [comment]
Hello,
anyone to confirm the merging ?
Thank you.

**Comment by etobella** [comment]
Can you squash the 3 migration commits?

**Comment by YvanDotet** [comment]
@etobella 
ok I think it's done

**Review by etobella — APPROVED** [review]

**Comment by YvanDotet** [comment]
Thanks

**Review by etobella — APPROVED** [review]

**Comment by YvanDotet** [comment]
We need something else to do the merging of the branche ?
Thanks.

**Comment by YvanDotet** [comment]
@etobella 
Is it ok to merge ?

**Review by albariera — APPROVED** [review]
LGTM :+1:

**Comment by etobella** [comment]
@OCA/management-systems-maintainers Can we ask for your review?

**Review by dreispt — APPROVED** [review]

**Comment by YvanDotet** [comment]
@dreispt 
@albariera 
@etobella 
Thank you to all of you.

**Pull request merged**
