### PR TITLE
[IMP] mgmtsystem_health_safety: __manifest__.py

### PR DESCRIPTION
**Pull request by andreampiovesana**
"application": False

### CODE REVIEW

**Comment by max3903** [comment]
@andreampiovesana Can you explain the reasoning behind this change?

**Comment by andreampiovesana** [comment]
image
mgmtsystem is an application but mgmtsystem_health_safety and mgmtsystem_environment no, right?
In total there are less than 80 ...

**Comment by max3903** [comment]
@andreampiovesana I would do the reverse: Quality, Environment, Health & Safety, Information Security are Apps and mgmtsystem (the base module) is hidden.

**Review by etobella — APPROVED** [review]

**Review by max3903 — APPROVED** [review]

**Pull request merged**
