### PR TITLE
[IMP] mgmtsystem_nonconformity: Model create multi

### PR DESCRIPTION
**Pull request by yassine-rhimi**

### CODE REVIEW

**Review by max3903 — APPROVED** [review]

**Comment by yassine-rhimi** [comment]
why this MR is not merging yet? Is there a problem?

**Comment by yassine-rhimi** [comment]
why this MR is not merging yet?

**Comment by yassine-rhimi** [comment]
I call you back to merge this pull req 
Thanks for your comprehension

**Pull request merged**
