### PR TITLE
[17.0] [MIG] mgmtsystem_action

### PR DESCRIPTION
**Pull request by m1k3lm**

### CODE REVIEW

**Comment by m1k3lm** [comment]
@mymage should the test coverage be fixed in the same PR as the migration?

**Comment by mymage** [comment]
> @mymage should the test coverage be fixed in the same PR as the migration?

I don't know really what is the actual policy. 
I had similar conditions in other migration PRs and I did my best to have all green.
If I remembe well some PSC merged it with some CodeCov not green.
So if you can and it is "simple" to complete the CodeCov, do it. If you do not reach the result, place here a message to [@]OCA/management-systems-maintainers.

**Comment by mymage** [comment]
@m1k3lm ... but the pandoc file is still here :-(

**Comment by m1k3lm** [comment]
> @m1k3lm ... but the pandoc file is still here :-(

Sorry, @mymage already deleted.

**Review by mymage — APPROVED** [review]
LGTM

**Review by max3903 — APPROVED** [review]

**Pull request merged**
