### PR TITLE
Initialize repo with unported modules and dot files

### PR DESCRIPTION
**Pull request by dreispt**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by max3903** [comment]
I suggest we remove all the modules in **unported**. Modules from 7.0 branch are more up-to-date than the ones from **unported**. We should use the modules from 7.0 branch to migrate them.

**Comment by dreispt** [comment]
Closes #15

**Comment by max3903** [comment]
:+1:

**Pull request merged**
