### PR TITLE
[11.0][MIG] mgmtsystem survey

### PR DESCRIPTION
**Pull request by jalzaga**
Module mgmtsystem_survey Migration to version 11.0 #200

### CODE REVIEW

**Comment by etobella** [comment]
@jalzaga Can you rebase it in order to review it?

**Comment by max3903** [comment]
@jalzaga I don't know what you did, but it didn't work as expected. This pull request now includes `mgmtsystem` and it should not.

Try to rebase using:
```
git remote add oca git@github.com:OCA/management-system.git
git fetch oca
git rebase -i oca/11.0
```

**Comment by aselcis** [comment]
I´ll reset and I'll do it again following your guidelines @max3903

**Comment by aselcis** [comment]
@max3903 First of all, thank you for your guide lines. 
This is exactly what I did. 
When I  did the "git rebase -i oca/11.0" it added the mgmtsystem module in my local directory,
Then it asked me to use git pull to merge the remote branch into mine.
The last step it asked me was a git push to publish the local commits
Please, let me know what is wrong.

**Comment by max3903** [comment]
@jalzaga You should not pull to merge. You should force the push:
```
git remote add oca git@github.com:OCA/management-system.git
git fetch oca
git rebase -i oca/11.0
git push -f origin 11.0-mig-mgmtsystem_survey
```
I am assuming that `origin` is `git@github.com:Aselcis-Consulting/management-system.git`

**Comment by aselcis** [comment]
Thank you @max3903 
However it was the "git rebase -i oca/11.0" command what added the mgmtsystem module to my local directory because it was merged recently.  The git push -f will add it to the remote git@github.com:Aselcis-Consulting/management-system.git
Anyway , what should I do?

**Comment by max3903** [comment]
@jalzaga Revert your merge commit (last commit on your branch) and push with `-f`
```
git reset --hard HEAD^
git push -f origin 11.0-mig-mgmtsystem_survey
```

**Comment by jalzaga** [comment]
This PR is ready to be tested

**Review by max3903 — APPROVED** [review]

**Review by ivantodorovich — APPROVED** [review]

**Pull request merged**
