### PR TITLE
Mig mgmtsystem manual to v. 10.0

### PR DESCRIPTION
**Pull request by eugen-don**
Mig mgmtsystem manuals to v. 10.0
depends 
- [x] https://github.com/OCA/management-system/pull/166 
- [x] https://github.com/OCA/knowledge/pull/122

### CODE REVIEW

**Comment by dreispt** [comment]
This PT includes the code from #166 .
Best practice is to include only the ported manual's code and in the PR description mention the dependency on other PRs.
This way the diff will show reviewers only the relevant code.

One functional question: this module adds the mgmtsystem manual, but that is also added on the mgmtsystem base module.
In my opinion, honoring the separation of concerns principle, all manual related features should go here.

**Comment by max3903** [comment]
@eugen-don Please rebase.

**Comment by eugen-don** [comment]
@max3903 there was only one commit left to rebase.
I rebased on origin/10.0 two commits into one...
Or did you mean i missed some other prior commits?

edit:
OK i removed the code from the other PR...
You can merge if it passes the checks

**Comment by max3903** [comment]
@eugen-don You need to rebase your branch on top of 10.0 to get mgmtystem migrated module.

```
git remote add oca git@github.com:oca/management-system.git
git fetch oca
git rebase -i oca/10.0
```
https://help.github.com/articles/about-git-rebase/

**Comment by eugen-don** [comment]
oh right you allready merged, i forgot

edit:
rebased on OCA/10.0

**Review by max3903 — APPROVED** [review]

**Review by grindtildeath — APPROVED** [review]

**Review by sbidoul — APPROVED** [review]

**Pull request merged**
