### PR TITLE
[IMP] mgmtsystem: Update icon

### PR DESCRIPTION
**Pull request by SMaciasOSI**
@max3903

### CODE REVIEW

**Comment by bosd** [comment]
How did you manage to create this V17 style icon?

**Comment by SMaciasOSI** [comment]
@bosd Our graphic designer made it

**Review by bosd — APPROVED** [review]
Looks awesome

**Review by ivantodorovich — CHANGES_REQUESTED** [review]
Looks awesome indeed.

Could you update also the `svg` file?

Both `png` and `svg` need to be updated and kept in sync.

The `svg` one is used to be able to easily maintain it in the future

**Comment by SMaciasOSI** [comment]
@ivantodorovich Done

**Review by ivantodorovich — APPROVED** [review]
Thanks ❤️ looks really good

I would check the dimensions of the `png` image. `591 x 587` seems too large IMO.
I encourage you to check the dimensions in standard Odoo apps logos, and then use the same dimensions.

**Review by max3903 — APPROVED** [review]

**Pull request merged**
