### PR TITLE
[REF] 8.0 mgmtsystem_manuals

### PR DESCRIPTION
**Pull request by llacroix**
No changes were required but depends on `document_page_approval` and `mgmtsystem`. 
- [x] It requires this PR to be merged first: https://github.com/OCA/management-system/pull/20
- [x] It also depends on this Knowledge PR: https://github.com/OCA/knowledge/pull/30

### CODE REVIEW

**Comment by llacroix** [comment]
Green :smile:

**Comment by bwrsandman** [comment]
Could you test own_company? It's the only line not tested.

**Comment by bwrsandman** [comment]
Coverage goes to 100% in #64

**Comment by bwrsandman** [comment]
:+1:

**Comment by max3903** [comment]
:+1:

**Pull request merged**
