### PR TITLE
[ADD] Add chatter to mgmtsystem.review

### PR DESCRIPTION
**Pull request by tobiaszehntner**
This adds the chatter to Reviews. The model mgmtsystem.review is the only one in the Management System that doesn't have chatter integrated. Actions, Non-conformities, Audits, Manuals, Forms, Flow Diagrams etc all have it already.

### CODE REVIEW

**Review by ivantodorovich — APPROVED** [review]
LGTM :+1: 

You need to install `pre-commit`  though, to get the green travis build

pre-approving

**Review by etobella — APPROVED** [review]

**Comment by tobiaszehntner** [comment]
> You need to install `pre-commit` though, to get the green travis build

I installed it on my local and all checks passed. The travis build failed because of a version conflict:
```bash
The conflict is caused by:
        pre-commit-dummy-package 0.0.0 depends on pylint==2.3.1
        pylint-odoo 3.0.3 depends on pylint==2.3.0
```
Is there anything I can do from my side?

**Comment by dreispt** [comment]
I reported this here: https://github.com/OCA/pylint-odoo/issues/330

**Comment by etobella** [comment]
rebase to the last branch, it has already been fixed on #375

**Pull request merged**
