### PR TITLE
[MIG] document_page_quality_manual: Migration to 17.0

### PR DESCRIPTION
**Pull request by dreispt**
Supersedes #568

### CODE REVIEW

**Review by max3903 — APPROVED** [review]

**Comment by max3903** [comment]
@pedrobaeza Looks like @ocabot is sleeping and doesn't want to merge... What should I do in this case if I cannot merge manually?

**Comment by pedrobaeza** [comment]
Just launch the command again

/ocabot merge nobump

**Comment by pedrobaeza** [comment]
Nop, @max3903, it seems really stuck...

@sbidoul maybe you can check the server to see what's happening?

**Comment by sbidoul** [comment]
Likely due to the expired cert causing webhook calls from GitHub to not go through. Please retry.

**Pull request merged**
