### PR TITLE
[MIG][13.0] mgmtsystem_nonconformity_product

### PR DESCRIPTION
**Pull request by mymage**
Migration to 13.0

### CODE REVIEW

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Review by ivantodorovich — APPROVED** [review]

**Comment by ivantodorovich** [comment]
@mymage I believe it's only pre-commit that's failing now :)
if you fix it we can merge

**Comment by mymage** [comment]
> @mymage I believe it's only pre-commit that's failing now :) if you fix it we can merge

I'm trying to fix it but I have some problem, be patient ;-)

**Pull request merged**
