### PR TITLE
[16.0][MIG] document_page_health_safety_manual

### PR DESCRIPTION
**Pull request by mymage**

### CODE REVIEW

**Review by max3903 — APPROVED** [review]

**Review by ivantodorovich — APPROVED** [review]
I think you can remove the commit `[UPD] Update document_page_health_safety_manual.pot`, or am I missing something?

**Comment by mymage** [comment]
> I think you can remove the commit `[UPD] Update document_page_health_safety_manual.pot`, or am I missing something?

I think you are right, i fix-up too much, I will try to restore it

**Comment by mymage** [comment]
> I think you can remove the commit `[UPD] Update document_page_health_safety_manual.pot`, or am I missing something?

I fix-up two other commit: what I know is to leave this type of commit

**Pull request merged**
