### PR TITLE
[FIX] Issue #202

### PR DESCRIPTION
**Pull request by max3903**
[FIX] Issue #202

### CODE REVIEW

**Comment by max3903** [comment]
@fdvarela Please review the fix.

**Comment by fdvarela** [comment]
It won't suffice. 

The email's html body is passed through a function defined in *email_template/email_template.py* line 131 
def _replace_local_links(self, cr, uid, html, context=None)

which replaces "img src" and "a href" urls prepending *web.base.url* (the right one)

I think the fix in the management system should only build the "path" part of the url and let the email_template function prepend the base url.

**Review by dreispt — APPROVED** [review]
LGTM

**Review by ivantodorovich — APPROVED** [review]
LGTM, although automated checks are not running.

**Comment by ivantodorovich** [comment]
Shouldn't this be ported to 9.0 and 10.0?

**Pull request merged**
