### PR TITLE
[10.0][FIX] Users selection in a review

### PR DESCRIPTION
**Pull request by benwillig**
A reviewer has no create/delete rights on users. Then, he is not able to select/deselect users on a review.

### CODE REVIEW

**Comment by dreispt** [comment]
Can you elaborate on the issue being fixed?

**Review by ThomasBinsfeld — APPROVED** [review]
Functional and code review :+1:

**Review by rami-wafaie — APPROVED** [review]
code review and testing :+1:

**Comment by benwillig** [comment]
@dreispt Same as https://github.com/OCA/management-system/pull/193

**Review by adrienpeiffer — COMMENTED** [review]
Could you change the version of this module ?

**Comment by benwillig** [comment]
Done!

**Review by adrienpeiffer — APPROVED** [review]
:+1: So, ready to merge :smile:

**Pull request merged**
