### PR TITLE
[MIG][15.0] mgmtsystem

### PR DESCRIPTION
**Pull request by YvanDotet**

### CODE REVIEW

**Comment by YvanDotet** [comment]
It is just to init the migration.

**Comment by YvanDotet** [comment]
Hello,
Is is ok to merge ?
Thank you.

**Comment by etobella** [comment]
No, you lost commit history and precommit is failing. Can you check migration guide from odoo community?
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0

**Comment by YvanDotet** [comment]
ok thank you

**Pull request closed without merging**
