### PR TITLE
[MIG] [13.0] mgmtsystem_audit

### PR DESCRIPTION
**Pull request by flachica**
@guadaltech

### CODE REVIEW

**Comment by flachica** [comment]
@NachoAlesLopez Please, can you take a look to this?

**Review by dreispt — APPROVED** [review]

**Review by max3903 — APPROVED** [review]

**Comment by max3903** [comment]
@flachica Can you look at the translation error at:
https://travis-ci.org/github/OCA/management-system/jobs/661107808#L1034

**Comment by flachica** [comment]
> @flachica Can you look at the translation error at:
> https://travis-ci.org/github/OCA/management-system/jobs/661107808#L1034

I will solve this after migrate the rest of module dependecies. Sorry for not to warning this earlier

**Comment by flachica** [comment]
@max3903 It seems that the translation issue was solved. Although I have to say I didn't see when it happened. How can I prevent it from happening again? with pre-commit?

**Comment by max3903** [comment]
@flachica I don't know. I am not sure to understand what happened. Let's see if it gets merged.

**Comment by flachica** [comment]
@max3903 Ups! I've made a [mistake](https://travis-ci.org/github/OCA/management-system/jobs/662145351#L1029). I will try to incorporate the test into pre-commit. But I'm afraid I'll need some clue to do it.

**Comment by flachica** [comment]
@max3903 Make this solved is tricky without the pre-commit script of ocabot merge command. The load German language fail. If import only this de.po (po of module) not fail.

**Comment by flachica** [comment]
Resolved. The problem was that in the .po file there were two different translations for the same res_id.

To find out which one I used I modified the file to add this code just before the sentence that failed to load the German language.

cr.execute("""SELECT name, lang, res_id, src, type, value, module, state, comments
                          FROM %s
                          WHERE type = 'model'
                          AND noupdate IS NOT TRUE
                        """ % (self._table, ))
for name, lang, res_id, src, type, value, module, state, comments in cr.fetchall():
    _logger.error('{}#{}#{}#{}#{}#{}#{}#{}#{}'.format(name, lang, res_id, src, type, value, module, state, comments))

**Pull request merged**
