### PR TITLE
[13.0] [MIG] mgmtsystem nonconformity hr

### PR DESCRIPTION
**Pull request by mymage**

### CODE REVIEW

**Comment by mymage** [comment]
@ivantodorovich Ping for a fast review (migration) :-)

**Comment by ivantodorovich** [comment]
same comments than `12.0` :)

**Comment by mymage** [comment]
@ivantodorovich I don't think I can do something with travis error.

**Comment by ivantodorovich** [comment]
Have you installed pre-commit in your local clone?
https://odoo-community.org/blog/the-oca-blog-1/post/black-isort-pre-commit-97

This is what travis is complaining for:
`mgmtsystem_audit/models/mgmtsystem_audit.py:163:13: E741 ambiguous variable name 'l`

**Comment by mymage** [comment]
Sorry I don't understand. I don't touch mgmtsystem_audit. I have to fix it? On my branch?

**Comment by ivantodorovich** [comment]
hmmm :thinking: weird.

Can you rebase on `OCA:13.0`?

**Comment by mymage** [comment]
Ok, but I need help, so wait a bit.

**Comment by mymage** [comment]
@ivantodorovich I did it but nothing changes. Suggestions?

**Comment by ivantodorovich** [comment]
Can you try fixing `mgmtsystem_audit/models/mgmtsystem_audit.py:163:13: E741 ambiguous variable name 'l'` in a separate commit?

**Comment by mymage** [comment]
> 
> 
> Can you try fixing `mgmtsystem_audit/models/mgmtsystem_audit.py:163:13: E741 ambiguous variable name 'l'` in a separate commit?

Ok
@ivantodorovich now all goes well

**Review by mamcode — APPROVED** [review]
LGTM

**Comment by mamcode** [comment]
@mymage Please report this PR in the issue #262

**Review by ivantodorovich — APPROVED** [review]

**Pull request merged**
