### PR TITLE
[11.0] [ADD] new module mgmtsystem_partner

### PR DESCRIPTION
**Pull request by mymage**
Ref. #263

### CODE REVIEW

**Review by marcelofrare — APPROVED** [review]
It works properly for me

**Comment by mymage** [comment]
I opened #348 for more audience :-)

**Comment by marcelsavegnago** [comment]
> I opened #348 for more audience :-)

https://github.com/OCA/management-system/pull/348#issuecomment-657112219

>  I don't know what the effort would be, but it may be more interesting to reuse the contact register by creating a new type called Quality. What do you think ?
> 
>https://github.com/odoo/odoo/blob/39dbc8b0935a44c3457938076ff5688fc0800414/odoo/addons/base/models/res_partner.py#L180

image

**Comment by mymage** [comment]
@etobella Can you kindly review this PR that locks #284, thanks

**Review by marcelsavegnago — APPROVED** [review]

**Comment by etobella** [comment]
Just a small question, why not adding this change directly to managament system base module?

**Comment by mymage** [comment]
> 
> 
> Just a small question, why not adding this change directly to managament system base module?

I'm not so confident with OCA world and the way things are managed. A suggestion that I got is to mantain separate modules for different funcionalities, but I have to learn where is the limit to ad a new one to an existing module or to do it all new.

So, in this case, thanks to your observation, I think it could be added to the base module*.
Do you think that is better to wait someone's other comment here or I can star a new PR do update another module?

*Thinking about that anyway, there is the problem that you can have different management systems, not only quality, with different contact reference so probabily it could be better to create a mgmtsystem_partner module where adding specific tab for "primary" systems (eg. quality, safety, ...).

**Comment by etobella** [comment]
Well, if this is the case, maybe we should need to add the configuration for each managment system. For example:

- `mgmtsystem_quality` adds `quality` partner
- `mgmtsystem_safety` (it currently does not exist) adds `safety` partner

And so on.

In any case, I think we should need to wait for another comment from a PSC member @OCA/management-systems-maintainers

**Comment by mymage** [comment]
@OCA/management-systems-maintainers
After a while I'm back here to try to close this PR part of a group. I know that it is for an old version but I will migrate it formward like other as soon as it will be approved.
Please let me know if there is something not right in the proposal.
Thanks

**Review by primes2h — APPROVED** [review]
LGTM

**Review by ivantodorovich — APPROVED** [review]

**Pull request merged**
