### PR TITLE
[IMP] mgmtsystem_audit: Model create multi

### PR DESCRIPTION
**Pull request by yassine-rhimi**

### CODE REVIEW

**Review by max3903 — APPROVED** [review]

**Comment by yassine-rhimi** [comment]
why this MR is not merging yet? Is there a problem?

**Comment by yassine-rhimi** [comment]
why this MR is not merging yet?

**Comment by max3903** [comment]
@yassine-rhimi 

We need:
2 reviews and 5 days
or
3 reviews

**Comment by yassine-rhimi** [comment]
I call you back to merge these pull req  number  538,539
thnks

**Pull request merged**
