### PR TITLE
[15.0][MIG] mgmtsystem_nonconformity_quality_control_oca

### PR DESCRIPTION
**Pull request by mymage**
Depends on:
- [x] https://github.com/OCA/manufacture/pull/912

### CODE REVIEW

**Review by ivantodorovich — APPROVED** [review]
LG, although this module has no unit tests.
It'd be good to add some

**Comment by mymage** [comment]
> LG, although this module has no unit tests. It'd be good to add some

Yes, I'll try to add test because I don't like to see Codecov red ;-)

I tried different way to fix the error on the dependencies test without lucky: do you know if and how to fix it?

**Comment by ivantodorovich** [comment]
Cool ;)

The dependencies test will be green after we remove these lines from the `test-requirements.txt` file:
```
# DONT MERGE
odoo-addon-quality-control-oca @ git+https://github.com/OCA/manufacture.git@refs/pull/912/head#subdirectory=setup/quality_control_oca
```

The thing is, if you remove them now, the other tests will fail (tests and runboat).
So, wait until the depended PR is merged, and then remove those lines from this PR.

Also, it's a good practice to put a reference to the depended PR in the description, to make it easy for reviewers to navigate to them. Something like this:

**Depends on:**
- https://github.com/OCA/manufacture/pull/912

**Comment by ivantodorovich** [comment]
/ocabot migration mgmtsystem_nonconformity_quality_control_oca

**Review by max3903 — APPROVED** [review]

**Comment by mymage** [comment]
@ivantodorovich Sorry the PR was merged before I had done the tests. I will do a dedicated PR to add them, just for exercise.

**Pull request merged**
