### PR TITLE
[IMP][8.0] Use email_template in ir_action_server

### PR DESCRIPTION
**Pull request by llacroix**

### CODE REVIEW

**Comment by llacroix** [comment]
Check https://github.com/savoirfairelinux/management-system/commit/de099ac93b29aa101e0faa8d775fb64f2bc9fab3 for major changes.

**Comment by llacroix** [comment]
Fix https://github.com/OCA/management-system/issues/65

**Comment by max3903** [comment]
:+1:

**Comment by bwrsandman** [comment]
:+1:

**Comment by dreispt** [comment]
:+1:

**Pull request merged**
