### PR TITLE
[13.0][MIG] mgmtsystem_manual: Migration to 13.0

### PR DESCRIPTION
**Pull request by ernestotejeda**
Depends on:
- [x] https://github.com/OCA/management-system/pull/268
- [x] https://github.com/OCA/knowledge/pull/228

~~As this module depends on https://github.com/OCA/management-system/pull/268 I have included here the commits of that PR so it can be functionally tested.~~

Cc @Tecnativa TT20482

### CODE REVIEW

**Comment by dreispt** [comment]
Why is the build green, if the dependencies are not ready?

**Comment by pedrobaeza** [comment]
Because the dependency is included here until it's merged, and then the PR is rebased.

**Comment by ernestotejeda** [comment]
As https://github.com/OCA/management-system/pull/268 is merged i rebased and cleaned up the commit history a bit

**Review by Tardo — COMMENTED** [review]
LGTM :+1:

**Comment by pedrobaeza** [comment]
@Tardo why don't you approve it instead of putting a comment?

**Review by pedrobaeza — APPROVED** [review]
But this can't merged until `document_page` is merged and `oca_dependencies.txt` must be removed.

**Review by Tardo — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please switch the oca_dependencies.txt file now that the dependency is merged

**Comment by ernestotejeda** [comment]
oca_dependencies.txt file updated

**Review by chienandalu — CHANGES_REQUESTED** [review]
@ernestotejeda you should rebase as there are merge conflicts now

**Review by dreispt — APPROVED** [review]

**Pull request merged**
