### PR TITLE
Mig mgmtsystem quality to v. 10.0

### PR DESCRIPTION
**Pull request by eugen-don**
Mig mgmtsystem quality to v. 10.0
depends: 
- [x] https://github.com/OCA/management-system/pull/173 audit
- [x] https://github.com/OCA/management-system/pull/175 manual
- [x] https://github.com/OCA/management-system/pull/171 review

### CODE REVIEW

**Comment by angelmoya** [comment]
Someone interested on this PR will go to OCA sprint Code?

**Comment by max3903** [comment]
@angelmoya I wish I could :( I will be available on the OCA IRC channel if necessary

**Comment by angelmoya** [comment]
I will try yo work on this topic, I put this PR as topic

**Comment by angelmoya** [comment]
@eugen-don you can update done work

**Comment by eugen-don** [comment]
Hi @angelmoya 
thats what id like to happen but it depends on https://github.com/OCA/management-system/pull/171

can you review and test https://github.com/OCA/management-system/pull/171 first?

thanks

**Comment by max3903** [comment]
@eugen-don You should be good to rebase now.

**Review by max3903 — APPROVED** [review]
:+1:

**Pull request merged**
