### PR TITLE
[REF] 8.0 mgmtsystem health safety 

### PR DESCRIPTION
**Pull request by llacroix**
Marked as installable 

Depends on:
- [x] #27
- [x] #51 
- [x] #53 
- [x] #28

### CODE REVIEW

**Comment by bwrsandman** [comment]
Please rename `health_safety.xml` as `mgmtsystem_system_data.xml`

**Comment by bwrsandman** [comment]
Depends on #27

**Comment by max3903** [comment]
IOError: File not found: mgmtsystem_health_safety/health_safety.xml

**Comment by dreispt** [comment]
:+1:

**Comment by max3903** [comment]
:+1:

**Pull request merged**
